export const PAYMENT_METHODS = Object.freeze({
  PAYMENT_CASH: 'PAYMENT_CASH',
  PAYMENT_CASH_POINT: 'PAYMENT_CASH_POINT',
  PAYMENT_POINT: 'PAYMENT_POINT',
})

export const ACTION_TYPES = Object.freeze({
  ADD_ITEMS: 'ADD_ITEMS',
  READ_LOCALSTORAGE: 'READ_LOCALSTORAGE',
})
